import express from "express";
import pinoHttp from "pino-http";
import { env } from "./env.ts";
import { logger } from "./lib/logger.ts";
import { attachAuth } from "./middleware/auth.ts";
import { killSwitch } from "./middleware/kill-switch.ts";
import { ipRateLimiter } from "./middleware/rate-limit.ts";
import { agentLiquidityRouter } from "./routes/agent-liquidity.ts";
import { agentPortfolioRouter } from "./routes/agent-portfolio.ts";
import { agentQueryRouter } from "./routes/agent-query.ts";
import { agentSendRouter } from "./routes/agent-send.ts";
import { agentSwapRouter } from "./routes/agent-swap.ts";
import { agentWalletsRouter } from "./routes/agent-wallets.ts";
import { complianceAdminRouter } from "./routes/compliance-admin.ts";
import { healthRouter } from "./routes/health.ts";
import { liquidityAddRouter } from "./routes/liquidity-add.ts";
import { liquidityRemoveRouter } from "./routes/liquidity-remove.ts";
import { poolCreateRouter } from "./routes/pool-create.ts";
import { poolStateRouter } from "./routes/pool-state.ts";
import { poolsRouter } from "./routes/pools.ts";
import { positionsRouter } from "./routes/positions.ts";
import { quoteRouter } from "./routes/quote.ts";
import { swapRouter } from "./routes/swap.ts";

const app = express();
app.set("trust proxy", 1);
app.use(pinoHttp({ logger }));
app.use(express.json());
app.use(ipRateLimiter);
app.use(killSwitch);
app.use(attachAuth);

app.use(healthRouter);
app.use(poolsRouter);
app.use(poolCreateRouter);
app.use(poolStateRouter);
app.use(liquidityAddRouter);
app.use(liquidityRemoveRouter);
app.use(positionsRouter);
app.use(quoteRouter);
app.use(swapRouter);
app.use(complianceAdminRouter);
app.use(agentWalletsRouter);
app.use(agentSendRouter);
app.use(agentSwapRouter);
app.use(agentLiquidityRouter);
app.use(agentQueryRouter);
app.use(agentPortfolioRouter);

app.listen(env.PORT, () => {
  logger.info({ port: env.PORT, env: env.NODE_ENV }, "server listening");
});
